Feature/unreachable notification
pagopa/pn-service-desk pull request #60
Opened 2023-09-25 11:44 UTC by ariannazafarana

2023-09-26 16:45 UTC, vincenzo-racca-pa requested changes

2023-09-27 07:48 UTC, ariannazafarana commented on src/main/java/it/pagopa/pn/service/desk/middleware/externalclient/pnclient/deliverypush/PnDeliveryPushClientImpl.java
> +                    log.error("Notification viewed in error {}", ex.getMessage());
fixato

2023-09-27 07:48 UTC, ariannazafarana commented on src/main/java/it/pagopa/pn/service/desk/action/impl/ValidationOperationActionImpl.java
> +                        throw new PnGenericException(IUNS_ALREADY_IN_PROGRESS, IUNS_ALREADY_IN_PROGRESS.getMessage());
fixato

2023-09-27 08:07 UTC, vincenzo-racca-pa requested changes

2023-09-27 08:22 UTC, ariannazafarana commented on src/main/java/it/pagopa/pn/service/desk/service/impl/NotificationServiceImpl.java
> +                        .onErrorResume(ex -> Mono.error(new PnGenericException(ERROR_GET_UNREACHABLE_NOTIFICATION, ERROR_GET_UNREACHABLE_NOTIFICATION.getMessage())))
aggiunto log

2023-09-27 08:23 UTC, vincenzo-racca-pa approved these changes

2023-09-27 10:33 UTC, merged